export type MentorSeed = {
  name: string;
  email: string;
  category: string;
  overlap: string;
  waveDay: number;
  subject: string;
  body: string;
};

export const MENTORS: MentorSeed[] = [
  {
    name: "Vivian Tu",
    email: "business@yourrichbff.com",
    category: "Female AI peer",
    overlap: "Left JP Morgan, 8M+ audience, immigrant",
    waveDay: 1,
    subject: "I Turned Down JP Morgan to Build, Like You Did",
    body: `<p>Hi Vivian,</p><p>A year ago I had a J.P. Morgan offer in hand and walked away from it to build something of my own, and you are a big part of why that felt like a plan rather than a gamble. You made the same call and turned it into something I find genuinely inspiring.</p><p>I'm Mehek, 20, a USC computer science student building an AI company on my own and documenting the whole thing publicly at @mehek.builds, working from the same belief you proved out, that the audience and the business are one and the same.</p><p>What you've built since leaving the desk is exactly where I want to be one day, and the part that fascinates me most is how you grew an audience that genuinely compounds. I'd love to grab fifteen minutes with you this week to learn how you grew that compounding audience. I'm at the very start of this and ready to learn from someone who has actually walked the path.</p><p>Thank you, and looking forward to it.</p><p>Mehek</p>`,
  },
  {
    name: "Wemimo Abbey",
    email: "wemimo@esusu.com",
    category: "Immigrant founder",
    overlap: "Immigrant who left finance, built Esusu to $1B+",
    waveDay: 6,
    subject: "An Immigrant Who Left Finance to Build, Like You",
    body: `<p>Hi Wemimo,</p><p>I came here as an immigrant and walked away from a finance offer to build something of my own, so your path from the bank to building Esusu from nothing is the story I keep coming back to when the leap feels heavy.</p><p>I'm Mehek, 20, a USC computer science student building an AI company on my own, and watching you leave finance and build something real out of nothing makes the road I'm on feel a lot less lonely.</p><p>What you built is exactly where I want to be one day, and the part I'm most curious about is the very beginning: how you found the first people who believed in you and bet on you after you left finance. I'd love to grab fifteen minutes with you this week to learn how you found those first believers. I'm right at that start now and ready to learn from someone who has lived it.</p><p>Thank you, Wemimo.</p><p>Mehek</p>`,
  },
  {
    name: "Kavitta Ghai",
    email: "kavitta@nectir.io",
    category: "Student founder",
    overlap: "Student founder, raised $2M+ at 24, does 10 founder calls a week",
    waveDay: 1,
    subject: "A Fellow Student Founder, Reaching Out",
    body: `<p>Hi Kavitta,</p><p>You raised real money while still a student, and since I'm trying to do exactly that right now, I had to reach out to someone walking the path a few steps ahead rather than someone three stages out of reach.</p><p>I'm Mehek, a USC computer science student building an AI company on my own while still in school, the same overlap of founder and student you pulled off.</p><p>That's exactly where I want to be, and since you're so generous with founder calls, the part I'd most love to learn is what actually convinced investors to back a founder that early, while you were still a student. I'd love to grab fifteen minutes with you this week to hear how you did it. I'm right at that point now and genuinely ready to learn from how you made it work.</p><p>Thank you, Kavitta.</p><p>Mehek</p>`,
  },
  {
    name: "Sahil Bloom",
    email: "sahil@sahilbloom.com",
    category: "Build-in-public peer",
    overlap: "Left finance, audience to a $10M fund, build-in-public",
    waveDay: 1,
    subject: "I Left Finance to Build in Public, Like You",
    body: `<p>Hi Sahil,</p><p>I walked away from a finance career to build something of my own out in the open, and you're a big part of why that felt like a real plan, since you made the same call and turned an audience into something genuinely substantial.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping it publicly at @mehek.builds, working from the same belief you proved out, that the audience you build can become the business itself.</p><p>What you've built since leaving finance is exactly where I want to be one day, and the part that fascinates me most is how the audience became genuinely fundable, not just large. I'd love to grab fifteen minutes with you this week to learn how you made that leap. I'm at the very start of this and ready to learn from someone who has walked the path.</p><p>Thank you, Sahil.</p><p>Mehek</p>`,
  },
  {
    name: "Allie K. Miller",
    email: "support@alliekmiller.com",
    category: "Female AI peer",
    overlap: "Female, AI, mentors-in-public, ~2M AI-business audience",
    waveDay: 1,
    subject: "Building in AI and in Public, Like You",
    body: `<p>Hi Allie,</p><p>I'm building in AI and documenting the whole thing out in the open, so you are the person I keep coming back to, because you built the largest AI-business audience there is and still mentor in public while doing it.</p><p>I'm Mehek, a USC computer science student building an AI company on my own and sharing every step publicly at @mehek.builds, working from the same bet you proved out, that building in AI and building an audience around it reinforce each other.</p><p>What you've built is exactly where I want to be one day, and the part I'm most curious about is which kind of content actually compounded for you early on versus what just spiked and faded. I'd love to grab fifteen minutes with you this week to learn how you figured that out. I'm right at that start now and eager to get it right.</p><p>Thank you, Allie.</p><p>Mehek</p>`,
  },
  {
    name: "Ruchi Sanghvi",
    email: "ruchi@southparkcommons.com",
    category: "VC open door",
    overlap: "Indian immigrant, female, funds pre-idea stage",
    waveDay: 6,
    subject: "An Indian Founder Following the Path You Paved",
    body: `<p>Hi Ruchi,</p><p>I came to the US from an Indian family to build, the same leap you made from Pune, and since you now fund the early, pre-idea stage I'm standing in right now, your story has stuck with me more than almost any other.</p><p>I'm Mehek, 20, a USC computer science student building an AI company of my own, and the way you back people before they even have the idea figured out is the most encouraging thing I've read in a while.</p><p>You kept choosing the harder, earlier thing at every step, and that's exactly where I want to be one day. I'd love to grab fifteen minutes with you this week to hear how you knew, back at your own start, that it was real enough to commit to fully. I'm right there now and ready to learn from someone who has lived both sides of it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Charu Sharma",
    email: "charu@fenrock.ai",
    category: "Vertical AI founder",
    overlap: "Indian immigrant, female, vertical-AI YC W26, built mentorship platform",
    waveDay: 1,
    subject: "A Fellow Immigrant Building Vertical AI",
    body: `<p>Hi Charu,</p><p>I came here as an immigrant and I'm building a vertical-AI company of my own, so watching you build one and get into YC made the exact path I'm on feel real rather than far-fetched.</p><p>I'm Mehek, a USC computer science student building a vertical-AI company solo, walking the same immigrant-founder road you did.</p><p>That's exactly where I want to be, and since you're so generous about mentoring, the part I'd most love to learn is how you got the wedge narrow enough to actually win. I'd love to grab fifteen minutes with you this week to hear how you did it. I'm right at that start now and genuinely ready to learn from someone walking the same path a step ahead.</p><p>Thank you, Charu.</p><p>Mehek</p>`,
  },
  {
    name: "Dina Alsamhan",
    email: "dina@qeen.ai",
    category: "Gulf founder",
    overlap: "Gulf/Kuwaiti, female, AI, built from Dubai, $10M MENA-record seed",
    waveDay: 2,
    subject: "A Fellow Dubai-Raised Founder, Reaching Out",
    body: `<p>Hi Dina,</p><p>I grew up in Dubai, and I'm building an AI company of my own from the same part of the world you did, so watching you close one of the region's largest rounds genuinely shifted how I think about where I can build from.</p><p>I'm Mehek, a USC computer science student, and seeing a Gulf-built AI team raise serious capital from here, rather than from an SF address, made the region feel like a real starting line instead of a place you have to leave.</p><p>That's exactly the path I want to be on, and I'd love to grab fifteen minutes with you this week to learn how you got a global fund to take a regional AI team seriously that early. I'm at the start of this and would value your perspective enormously.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Ghita Houir Alami",
    email: "founders@zeroentropy.dev",
    category: "Young immigrant founder",
    overlap: "Moroccan immigrant, female, very young, YC W25 + $4.2M",
    waveDay: 2,
    subject: "A Fellow International Founder in AI",
    body: `<p>Hi Ghita,</p><p>I'm an international student building in AI on my own, so watching you get into YC and raise for hard AI infrastructure this young made the path I'm on feel genuinely possible.</p><p>I'm Mehek, a USC computer science student building an AI company solo, walking the same international-founder road in AI that you did.</p><p>That's exactly where I want to be one day, and the part I'm most curious about is how you got investors to underwrite the hard infrastructure bet before there was deep revenue behind it. I'd love to grab fifteen minutes with you this week to learn how you did it. I'm right at that start now and genuinely ready to learn from someone a step ahead on the same path.</p><p>Thank you, Ghita.</p><p>Mehek</p>`,
  },
  {
    name: "Sonya Jin",
    email: "sonya@phinity.ai",
    category: "Young founder",
    overlap: "Very young, female, build-in-public, PearX + $5.5M",
    waveDay: 2,
    subject: "A Fellow Young Founder Building in Public",
    body: `<p>Hi Sonya,</p><p>I'm building a company on my own and documenting the whole thing out in the open, so when I saw you get into a top accelerator and raise young while sharing the build as you went, I knew I had to reach out to you specifically rather than someone three stages ahead.</p><p>I'm Mehek, a USC computer science student building a product solo and shipping in public as I go, the same way you did on your own road.</p><p>You're a step ahead on the exact path I'm walking, and the part I'd most love to learn is whether building in public actually moved your raise or whether it really came down to the technical work. I'd love to grab fifteen minutes with you this week to hear how you'd weigh it. I'm right at that start now and genuinely ready to learn from how you did it.</p><p>Thank you, Sonya.</p><p>Mehek</p>`,
  },
  {
    name: "Jaleh Rezaei",
    email: "jaleh@mutinyhq.com",
    category: "Immigrant AI founder",
    overlap: "Immigrant, female, AI, Mutiny $71M+",
    waveDay: 6,
    subject: "An Immigrant Founder Following Your AI Path",
    body: `<p>Hi Jaleh,</p><p>I came to the US as an immigrant to build, the same leap you made, and watching you scale a serious AI company from that starting point is a big part of why the road I'm on feels real rather than reckless.</p><p>I'm Mehek, 20, a USC computer science student building a vertical-AI company of my own, working from the belief you proved out, that an outsider can build something that genuinely matters here.</p><p>What you've built is exactly where I want to be one day, and the part that fascinates me most is how you got investors to believe in the wedge before the metrics made it obvious. I'd love to grab fifteen minutes with you this week to learn how you did it. I'm at the very start of this and ready to learn from someone who has actually walked the path.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Tina Huang",
    email: "tina@lonelyoctopus.com",
    category: "Build-in-public peer",
    overlap: "Asian-American, ex-Goldman, AI, female, 1M+ subs to a company",
    waveDay: 2,
    subject: "I Left Finance to Build, Like You Did",
    body: `<p>Hi Tina,</p><p>You left Goldman to bet on yourself, and a year ago I walked away from a finance offer to build something of my own, so your path is one I keep coming back to when I want proof the leap leads somewhere real.</p><p>I'm Mehek, a USC computer science student building an AI company on my own and documenting the whole thing publicly at @mehek.builds, working from the belief you proved out, that the audience and the business are one and the same.</p><p>What you've built since leaving the desk is exactly where I want to be one day, and the part I'm most curious about is how your audience actually converted into paying customers. I'd love to grab fifteen minutes with you this week to learn how you made that leap. I'm right at that point now and eager to get it right.</p><p>Thank you, Tina.</p><p>Mehek</p>`,
  },
  {
    name: "Jenny Hoyos",
    email: "jenny@jennyhoyos.com",
    category: "Young creator",
    overlap: "Very young, female, immigrant-family, 9-11M audience as a teen",
    waveDay: 3,
    subject: "Building an Audience Young, Like You Did",
    body: `<p>Hi Jenny,</p><p>You built a massive audience while young and made virality look like engineering rather than luck, and that's exactly the thing I'm trying to learn right now, so I had to write to you.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping something new every week out in the open at @mehek.builds, treating the content as the product itself rather than the marketing around it.</p><p>What you've built is exactly where I want to be one day, and the part I'm most curious about is the single thing you check before posting that most predicts whether it pops. I'd love to grab fifteen minutes with you this week to learn how you think about that. I'm right at the start of this and eager to get it right.</p><p>Thank you for building so openly.</p><p>Mehek</p>`,
  },
  {
    name: "Maggie Sellers",
    email: "maggie@hotsmartrich.com",
    category: "Female creator-founder",
    overlap: "Immigrant, ex-finance, female, 275k audience to media + VC syndicate",
    waveDay: 3,
    subject: "I Left Finance to Build, Like You Did",
    body: `<p>Hi Maggie,</p><p>You left finance to bet on yourself, and a year ago I walked away from a finance offer to build something of my own, so your path is one I keep coming back to when I want proof the leap leads somewhere real.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping in the open at @mehek.builds, treating the content as the business itself rather than the marketing around it.</p><p>What you've built is exactly where I want to be one day, and the part that fascinates me most is why you layered an investing syndicate on top of the media company instead of just monetizing the audience. I'd love to grab fifteen minutes with you this week to learn how you thought about that. I'm at the start of this and genuinely ready to learn from how you did it.</p><p>Thank you, Maggie.</p><p>Mehek</p>`,
  },
  {
    name: "Zach Yadegari",
    email: "zach@calai.app",
    category: "Young founder",
    overlap: "Very young, AI, no pedigree, AI app to ~$30M ARR as a teen",
    waveDay: 3,
    subject: "A Fellow Young Builder, No Pedigree, Reaching Out",
    body: `<p>Hi Zach,</p><p>You built an AI app to real revenue as a teenager, with no pedigree behind you, and that's the clearest proof I've found that the road I'm on actually leads somewhere, which is why I wanted to reach out to you specifically.</p><p>I'm Mehek, a USC computer science student building an AI product on my own, working from the same belief you proved out, that being young and uncredentialed is no reason to wait.</p><p>You're a step ahead on the exact path I'm walking, and the part I'd most love to learn is the single highest-leverage thing you did going from a working app to real growth. Could we find fifteen minutes this week? I'm at the start of this and genuinely ready to learn from how you did it.</p><p>Thank you, Zach.</p><p>Mehek</p>`,
  },
  {
    name: "Dickie Bush",
    email: "dickie@ship30for30.com",
    category: "Build-in-public peer",
    overlap: "Left BlackRock, pro-beginner, 600k audience to $1M+/yr",
    waveDay: 3,
    subject: "I Left Finance to Build, Like You Did",
    body: `<p>Hi Dickie,</p><p>You left BlackRock to bet on yourself, and a year ago I walked away from a finance offer to build something of my own, so your path is one I keep coming back to when I want proof the leap leads somewhere real.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping in the open at @mehek.builds, treating the writing and the content as the business itself rather than the marketing around it.</p><p>What you've built since leaving finance is exactly where I want to be one day, and the part I'm most curious about is what made people trust you enough to pay before you had the track record. I'd love to grab fifteen minutes with you this week to learn how you did it. I'm right at that point now and eager to get it right.</p><p>Thank you, Dickie.</p><p>Mehek</p>`,
  },
  {
    name: "Nicolas Cole",
    email: "cole@ship30for30.com",
    category: "Build-in-public peer",
    overlap: "No pedigree, pro-beginner, 600k audience + multi-$M",
    waveDay: 3,
    subject: "Content Is My Whole Business Too",
    body: `<p>Hi Nicolas,</p><p>You built a real business out of content with no credentials and no pedigree, winning purely on the writing itself, and that's the clearest proof I've found that the road I'm on actually leads somewhere real.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping something new in the open at @mehek.builds, treating the content as the product itself rather than the marketing around it.</p><p>What you've built is exactly where I want to be one day, and the part I'm most curious about is how you converted readers into paying customers without it ever feeling like selling. I'd love to grab fifteen minutes with you this week to learn how you made that leap. I'm right at that point now and eager to get it right.</p><p>Thank you for building so openly.</p><p>Mehek</p>`,
  },
  {
    name: "Marie Martens",
    email: "marie@tally.so",
    category: "Build-in-public peer",
    overlap: "Female, build-in-public, near-solo, Tally ~$2M ARR no VC",
    waveDay: 4,
    subject: "Building in Public, Betting on Revenue Over a Raise",
    body: `<p>Hi Marie,</p><p>You're the example I keep coming back to when I doubt the path I'm on, because you built in public and bet on real revenue rather than giving the company away to investors, which is exactly the bet I'm making.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping it out in the open, and seeing a woman reach real revenue lean and in public matters more to me than I can fit into an email.</p><p>That's the kind of company I want to build, and what I'd most love to learn is the earliest part: the highest-leverage thing you did to reach your first real revenue. Could we find fifteen minutes this week? I'm at the very start and eager to learn from how you did it.</p><p>Thank you, Marie.</p><p>Mehek</p>`,
  },
  {
    name: "Marie Poulin",
    email: "hello@mariepoulin.com",
    category: "Build-in-public peer",
    overlap: "Female, audience-funds-product, pro-beginner, ~$40k/mo solo",
    waveDay: 4,
    subject: "Content Is My Whole Business Too",
    body: `<p>Hi Marie,</p><p>You grew a solo business by letting a free audience pull people into a paid product, and that's exactly the model I'm trying to get right, so I had to write to the person who made it look so natural.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping something new in the open at @mehek.builds, treating the content as the product itself rather than the marketing around it.</p><p>What you've built is exactly where I want to be one day, and the part I'm most curious about is how you decided what to give away free versus hold back for the paid product. I'd love to grab fifteen minutes with you this week to learn how you drew that line. I'm right at that point now and eager to get it right.</p><p>Thank you for building so openly.</p><p>Mehek</p>`,
  },
  {
    name: "Cassey Ho",
    email: "cassey@blogilates.com",
    category: "Female creator-founder",
    overlap: "Immigrant refused safe path, female, 15M followers, two 8-fig brands solo",
    waveDay: 4,
    subject: "I Walked Away From the Safe Path Too",
    body: `<p>Hi Cassey,</p><p>You refused the safe career path your family pushed you toward and built it into something entirely your own, and a year ago I made the same kind of call against the safe option, which is why your story has stuck with me so much.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping in the open at @mehek.builds, treating the content as the business itself rather than the marketing around it.</p><p>What you've built solo into real companies, with no investors, is exactly where I want to be one day, and the part I'm most curious about is how you knew your audience was ready for a product and not just there to watch. I'd love to grab fifteen minutes with you this week to learn how you made that call. I'm right at that point now and eager to get it right.</p><p>Thank you for building so openly.</p><p>Mehek</p>`,
  },
  {
    name: "Henrique Dubugras",
    email: "henrique@brex.com",
    category: "Young immigrant founder",
    overlap: "Immigrant, very young, dropout, Brex unicorn in ~2 yrs",
    waveDay: 6,
    subject: "A Fellow Young Founder Who Built as an Outsider",
    body: `<p>Hi Henrique,</p><p>You came in as an outsider with no US network and built something massive while you were still young, and that is the exact wall I'm staring at right now, so I had to write to you specifically.</p><p>I'm Mehek, a USC computer science student building an AI company on my own and shipping it out in the open, working from the belief that you don't need a local pedigree to build something that matters.</p><p>What you pulled off as a young founder with no inherited network is precisely where I want to be one day, and the part that fascinates me most is how the early investors got there. I'd love to grab fifteen minutes with you this week to learn how you got people to bet on a young founder with no local track record. I'm right at that start and ready to learn from someone who lived it.</p><p>Thank you, Henrique.</p><p>Mehek</p>`,
  },
  {
    name: "Parth Garg",
    email: "parth.garg@aspora.com",
    category: "Gulf founder",
    overlap: "Gulf-raised Indian, Stanford dropout, young, Aspora ~$500M val",
    waveDay: 6,
    subject: "A Fellow Gulf-Raised Young Founder, Reaching Out",
    body: `<p>Hi Parth,</p><p>I grew up in the Gulf in an Indian family, and watching you build a real company so young from a similar starting point made the whole thing feel like a plan rather than a long shot, so I wanted to reach out to you directly.</p><p>I'm Mehek, a USC computer science student building an AI company on my own and shipping it in public as I go, betting that where you start doesn't cap where you end up.</p><p>You built something serious while you were still early in your own journey, and that is exactly where I want to be one day. The part I'd most love to learn is the very beginning. I'd love to grab fifteen minutes with you this week to hear how you found your first two or three real believers. I'm at the start of this and eager to get it right.</p><p>Thank you, Parth.</p><p>Mehek</p>`,
  },
  {
    name: "Jyoti Bansal",
    email: "jyoti@harness.io",
    category: "Indian immigrant founder",
    overlap: "Indian, visa-fight (your F-1), technical, AppDynamics $3.7B exit",
    waveDay: 7,
    subject: "An Indian Founder Following the Path You Paved",
    body: `<p>Hi Jyoti,</p><p>You built a multibillion-dollar company as an Indian immigrant through years of visa uncertainty, and as someone building right now on an F-1, your story is the one I keep coming back to when the paperwork feels like the whole game.</p><p>I'm Mehek, 20, a USC computer science student building an AI company on my own, working from the belief you proved out, that you can build something huge without waiting for your status to feel settled.</p><p>What you did despite all that uncertainty is exactly where I want to be one day, and the part that stays with me most is the decision to commit anyway. I'd love to grab fifteen minutes with you this week to hear how you decided to go all in instead of waiting for the paperwork to clear. I'm right at that fork now and ready to learn from someone who has lived it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Deepica Mutyala",
    email: "deepica@livetinted.com",
    category: "Indian creator-founder",
    overlap: "Indian, female, audience-to-funded, 1M audience to a $10M Series A",
    waveDay: 7,
    subject: "Turning an Audience Into a Real Company, Like You Did",
    body: `<p>Hi Deepica,</p><p>You turned a viral audience into a funded company, and as a fellow Indian builder doing the same thing in reverse, building the audience and the company together, your path is the clearest proof I've found that this actually works.</p><p>I'm Mehek, a USC computer science student building an AI company on my own and documenting the whole thing publicly at @mehek.builds, working from the belief that the audience and the business are one and the same.</p><p>What you built off your own audience is exactly where I want to be one day, and the part that fascinates me most is the investor side of it. I'd love to grab fifteen minutes with you this week to learn how you got investors to underwrite your audience as a real moat. I'm at the very start of this and ready to learn from how you did it.</p><p>Thank you, Deepica.</p><p>Mehek</p>`,
  },
  {
    name: "Gergely Orosz",
    email: "gergely@pragmaticengineer.com",
    category: "Build-in-public peer",
    overlap: "Immigrant, build-in-public, solo software, 1M readers, $1.5M+/yr solo",
    waveDay: 7,
    subject: "Building in Public, Growing a Software Audience",
    body: `<p>Hi Gergely,</p><p>You built a huge software audience and a real business solo and in the open, and as an immigrant doing the same thing from my own corner of the world, that is the exact path I'm betting on, so I had to write to you.</p><p>I'm Mehek, a USC computer science student building an AI product on my own and shipping it in public every week at @mehek.builds, treating the writing and the building as one thing rather than marketing around it.</p><p>What you've built solo is exactly where I want to be one day, and the part I'm most curious about is the earliest stretch. I'd love to grab fifteen minutes with you this week to learn what compounded your subscriber growth most in the early days. I'm right at that beginning now and eager to get it right.</p><p>Thank you, Gergely.</p><p>Mehek</p>`,
  },
  {
    name: "Anada Lakra",
    email: "anada@boldvoice.com",
    category: "Immigrant founder",
    overlap: "Immigrant, female, near-solo, YC + $21M + $10M ARR",
    waveDay: 2,
    subject: "A Fellow Immigrant Founder Running Lean",
    body: `<p>Hi Anada,</p><p>You got into YC and scaled efficiently while running lean, and as a fellow immigrant woman building nearly solo, that is exactly the path I'm on, so I wanted to reach out to you specifically.</p><p>I'm Mehek, a USC computer science student building an AI company on my own and shipping it in public as I go, betting that a small, sharp team can go a long way.</p><p>What you've built running this lean is exactly where I want to be one day, and the part I'd most love to learn is the very start of the YC story. I'd love to grab fifteen minutes with you this week to hear what convinced YC the wedge was worth funding before the revenue proved it. I'm right at that point now and genuinely ready to learn from how you did it.</p><p>Thank you, Anada.</p><p>Mehek</p>`,
  },
  {
    name: "Tracy Young",
    email: "tracy@tigereye.com",
    category: "Immigrant founder",
    overlap: "Refugee-immigrant, female, YC, PlanGrid exit (~$875M)",
    waveDay: 7,
    subject: "A Fellow Immigrant Woman on the YC Path",
    body: `<p>Hi Tracy,</p><p>You built a company through YC all the way to a real exit as a rare woman in a male-dominated space, and as a fellow immigrant woman starting down that same road, your story is the one I hold onto, so I had to write to you.</p><p>I'm Mehek, 20, a USC computer science student building an AI company on my own, working from the belief that the odds being stacked doesn't mean the outcome is.</p><p>What you built to a real exit is exactly where I want to be one day, and the part I'd most love to learn is the very beginning. I'd love to grab fifteen minutes with you this week to hear how you grew your earliest believers and traction. I'm right at that start now and ready to learn from someone who has lived it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Mar Hershenson",
    email: "mhershenson@pear.vc",
    category: "VC open door",
    overlap: "Immigrant (Spain), technical, female, Pear VC, 3 startups",
    waveDay: 7,
    subject: "A Fellow Immigrant Technical Founder, Reaching Out",
    body: `<p>Hi Mar,</p><p>You came over from Spain, founded multiple startups as a technical woman, and now back founders at the very earliest moment, which is exactly the moment I'm in, so I wanted to reach out to you specifically.</p><p>I'm Mehek, 20, a USC computer science student building an AI company on my own, and the way you invest in people at the pre-idea stage is the most encouraging thing I've read in a while.</p><p>You kept choosing the harder, earlier path at every step, and that is exactly where I want to be one day. I'd love to grab fifteen minutes with you this week to hear what you wish someone had told you back when you were at the stage I'm at now. I'm right there, and ready to learn from someone who has lived both sides of it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "May Habib",
    email: "may@writer.com",
    category: "Middle East founder",
    overlap: "Middle East, ex-banking, female, AI, Writer (~$1.9B)",
    waveDay: 8,
    subject: "I Walked Away From Finance to Build, Like You Did",
    body: `<p>Hi May,</p><p>You walked away from a banking career and built a major AI company, and as someone with Middle East roots who made the same kind of leap away from finance, your call is the one I keep measuring my own against.</p><p>I'm Mehek, 20, a USC computer science student building an AI company on my own, working from the same belief you proved out, that the safer path isn't always the right one.</p><p>What you've built since leaving banking is exactly where I want to be one day, and the part that stays with me most is the decision itself. I'd love to grab fifteen minutes with you this week to hear how you knew the finance walk-away was the right call and not reckless. I'm right at that crossroads now and ready to learn from someone who has lived it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Lenny Rachitsky",
    email: "lenny@lennyrachitsky.com",
    category: "Build-in-public peer",
    overlap: "1M-audience, platforms beginners, 1.2M subs, $2M+/yr solo",
    waveDay: 4,
    subject: "Building in Public, Learning From How You Did It",
    body: `<p>Hi Lenny,</p><p>You turned a 1M+ audience into a solo business and you genuinely lift up early builders, which is rarer than it sounds, so I had to write to the person actually doing it.</p><p>I'm Mehek, a USC computer science student building an AI product on my own and shipping it in public every week at @mehek.builds, treating the writing and the building as one thing rather than marketing around it.</p><p>What you've built solo is exactly where I want to be one day, and the part I'm most curious about is the earliest trust. I'd love to grab fifteen minutes with you this week to learn what made readers trust you enough to pay in the early days. I'm right at that start now and eager to learn from how you did it.</p><p>Thank you, Lenny.</p><p>Mehek</p>`,
  },
  {
    name: "Devaki Raj",
    email: "devaki.raj@saabinc.com",
    category: "Indian immigrant founder",
    overlap: "Indian immigrant-family, female, AI, YC + $18M + exit to Saab",
    waveDay: 8,
    subject: "An Indian Founder Following the Path You Paved",
    body: `<p>Hi Devaki,</p><p>I come from an Indian immigrant family that made the leap to the US to build, and you took an AI company from a standing start all the way through Y Combinator to an acquisition, which is the exact arc I think about constantly as I start mine.</p><p>I'm Mehek, 20, a USC computer science student building an AI company on my own, and seeing someone from a background like ours go from zero to a real exit makes the whole thing feel like a plan rather than a dream.</p><p>That's exactly where I want to be one day, and the part I'd most love to learn is what you underweighted early on, the thing you'd tell a young solo founder to take far more seriously from day one. I'd love to grab fifteen minutes with you this week to hear how you'd do it again. I'm right at the start and ready to learn.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Divya Gugnani",
    email: "divya@5sens.co",
    category: "Indian immigrant founder",
    overlap: "Indian, left Goldman, female, 4 companies multiple exits",
    waveDay: 8,
    subject: "An Indian Founder Who Left Finance to Build",
    body: `<p>Hi Divya,</p><p>I come from an Indian family and walked away from a prestige finance seat to build something of my own, the same call you made when you left Goldman, which is why your path has stuck with me so much.</p><p>I'm Mehek, 20, a USC computer science student building a company on my own, and watching you leave that world and go on to build multiple companies all the way to exits is the clearest proof I've found that the road I'm choosing actually leads somewhere real.</p><p>That's exactly where I want to be one day, and what fascinates me most is how you got comfortable that founding was the better long-term bet after giving up a seat that prestigious. I'd love to grab fifteen minutes with you this week to hear how you knew. I'm at the very start of this and ready to learn from someone who has lived it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Kat Norton",
    email: "kat@miss-excel.com",
    category: "Female creator-founder",
    overlap: "Female, solo, content-is-the-build, 2M followers to 7-fig solo business",
    waveDay: 4,
    subject: "Content Is My Whole Business Too",
    body: `<p>Hi Kat,</p><p>You turned your own audience into a solo seven-figure business off your own products, and that is the exact thing I had to write to you about, because it's the road I'm betting my own on.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping something new every week out in the open at @mehek.builds, treating the content as the product itself rather than the marketing around it. Watching you build a real business off your audience, with no investors, is the clearest proof I've found that this actually works.</p><p>The part I'm most curious about is how you knew your audience was ready to buy and not just watch. I'd love to grab fifteen minutes with you this week to learn how you made that leap. I'm right at that point now and eager to get it right.</p><p>Thank you for building so openly.</p><p>Mehek</p>`,
  },
  {
    name: "Lara Acosta",
    email: "lara@literallyacademy.com",
    category: "Female creator-founder",
    overlap: "International (moved at 15), female, from zero to #1 female LinkedIn creator",
    waveDay: 5,
    subject: "A Fellow Creator Who Built From Zero",
    body: `<p>Hi Lara,</p><p>You moved abroad young and went from zero to one of the top creators in your space in under two years, and as someone living far from home and building an audience from nothing right now, that arc is exactly the one I keep studying.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping in public every week at @mehek.builds, growing an audience from scratch as I go. Seeing you compound that fast, that far from where you started, is genuinely inspiring to me.</p><p>The part I'd most love to learn is what actually changed for you, the thing that took you from invisible to truly compounding. I'd love to grab fifteen minutes with you this week to hear how you found it. I'm right in that early phase now and ready to learn from how you did it.</p><p>Thank you, Lara.</p><p>Mehek</p>`,
  },
  {
    name: "Polina Marinova Pompliano",
    email: "polina@readtheprofile.com",
    category: "Build-in-public peer",
    overlap: "Immigrant, left prestige media, female, solo 7-fig newsletter + book",
    waveDay: 5,
    subject: "I Left a Prestige Seat to Build in Public",
    body: `<p>Hi Polina,</p><p>You left a prestige media seat to build a solo, audience-led business of your own, and as an immigrant who walked away from a safe path to do the same thing, that's the exact leap I keep coming back to.</p><p>I'm Mehek, a USC computer science student building a product on my own and writing in public every week at @mehek.builds, betting on my own audience the way you bet on yours. Watching you turn that bet into a real solo business is the clearest proof I've found that this road actually leads somewhere.</p><p>The part I'm most curious about is what actually compounded your subscriber growth in that first year. I'd love to grab fifteen minutes with you this week to hear how you did it. I'm right at that early stage now and eager to learn from how you got it right.</p><p>Thank you, Polina.</p><p>Mehek</p>`,
  },
  {
    name: "Rebecca Shostak",
    email: "rebecca@flodesk.com",
    category: "Female creator-founder",
    overlap: "Female, build-in-public, Flodesk creator-first, Female Founders 500",
    waveDay: 8,
    subject: "Building in Public on Audience and Word of Mouth",
    body: `<p>Hi Rebecca,</p><p>You built a creator-first company on audience and word of mouth rather than a heavy push, and as someone building her own company out in the open right now, that's exactly the kind of growth I'm trying to understand.</p><p>I'm Mehek, a USC computer science student building a product on my own and shipping it in public as I go, betting on the same audience-led, word-of-mouth approach you proved out.</p><p>That's the kind of company I want to build, and what I'd most love to learn is the one growth lever you wish you had pulled sooner. I'd love to grab fifteen minutes with you this week to hear what it was. I'm at the very start of this and genuinely ready to learn from how you did it.</p><p>Thank you, Rebecca.</p><p>Mehek</p>`,
  },
  {
    name: "Rana el Kaliouby",
    email: "rana@bluetulip.vc",
    category: "Gulf founder",
    overlap: "Gulf-raised, female, AI founder to VC, Affectiva",
    waveDay: 5,
    subject: "A Fellow Gulf-Raised Woman in AI, Reaching Out",
    body: `<p>Hi Rana,</p><p>I grew up in the Gulf, and you built a pioneering AI company as a woman raised in this same part of the world, which genuinely shifted how I think about where a female founder can start from.</p><p>I'm Mehek, 20, a USC computer science student building an AI company of my own, and seeing a Gulf-raised woman pioneer real AI made the region feel like a true starting line rather than somewhere you have to leave first.</p><p>That's exactly the path I want to be on, and what I'd most love to learn is how you think about what actually makes an early company fundable. I'd love to grab fifteen minutes with you this week to hear how you see it. I'm at the start of this and would value your perspective enormously.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Ankita Vashistha",
    email: "ankita@strongher.vc",
    category: "Female VC",
    overlap: "Cross-border immigrant, female, founded India's first women-VC fund",
    waveDay: 8,
    subject: "A Cross-Border Founder Backing Women, Like You",
    body: `<p>Hi Ankita,</p><p>I'm a cross-border immigrant founder building my own company, and you built whole funds to back women founders, which is why your work has stuck with me as I start out on my own.</p><p>I'm Mehek, 20, a USC computer science student building a company on my own, and seeing someone build the capital and the conviction to put women founders first is the kind of thing that makes this path feel a lot less lonely.</p><p>That's exactly the world I want to be building in, and what I'd most love to learn is the single question you wish more young women founders actually asked you. I'd love to grab fifteen minutes with you this week to hear it. I'm right at the start and ready to learn from someone who has backed people like me.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Priyanka Kulkarni",
    email: "priyanka@casium.com",
    category: "Vertical AI founder",
    overlap: "Indian, female, vertical AI from her visa pain, AI2, $5M seed",
    waveDay: 5,
    subject: "An Indian Founder Building From My Own Visa Story",
    body: `<p>Hi Priyanka,</p><p>I'm an Indian founder on an F-1, and you turned your own visa journey into a vertical-AI product, which is almost exactly the path I'm walking, so I had to reach out to you specifically.</p><p>I'm Mehek, a USC computer science student building a vertical-AI company on my own, and seeing you take the pain you lived through and build a real product around it is the clearest proof I've found that the road I'm on actually leads somewhere.</p><p>That's exactly where I want to be, and what I'd most love to learn is how you validated that your wedge was the right first one to commit to. I'd love to grab fifteen minutes with you this week to hear how you knew. I'm right at that point now and eager to get the first call right.</p><p>Thank you, Priyanka.</p><p>Mehek</p>`,
  },
  {
    name: "Suchi Saria",
    email: "ssaria@cs.jhu.edu",
    category: "Vertical AI founder",
    overlap: "Intl student, female, vertical AI, built Bayesian Health",
    waveDay: 9,
    subject: "An International Student Building Vertical AI Too",
    body: `<p>Hi Suchi,</p><p>I came to the US as an international student to build, and you went on to create a real vertical-AI company, which is the exact lane I'm in right now, so your path is one I study closely.</p><p>I'm Mehek, 20, a USC computer science student building a vertical-AI company of my own, and seeing someone who started where I did go on to build something this real makes the whole thing feel like a plan rather than a leap.</p><p>That's exactly where I want to be one day, and what I'd most love to learn is how you chose which vertical to own first when the surface area felt endless. I'd love to grab fifteen minutes with you this week to hear how you decided. I'm right at that choice now and ready to learn from how you made it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Bindu Reddy",
    email: "breddy@abacus.ai",
    category: "Indian immigrant founder",
    overlap: "Indian immigrant, female, bootstrapped Abacus.AI to real revenue",
    waveDay: 9,
    subject: "An Indian Founder Following the Path You Paved",
    body: `<p>Hi Bindu,</p><p>I came to the US from an Indian family to build an AI company of my own, the same leap you made, and the way you bootstrapped a real AI business to actual revenue is exactly the proof I keep coming back to when the path feels uncertain.</p><p>I'm Mehek, 20, a USC computer science student building a vertical-AI company on my own, and what you've built is precisely where I want to be one day.</p><p>The part that fascinates me most is how you found an enterprise-AI wedge that customers would actually pay for early, rather than chasing a problem nobody would fund. I'd love to grab fifteen minutes with you this week to learn how you did it. I'm right at that start and genuinely ready to learn from someone who has lived it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Harshita Arora",
    email: "harshita@atob.com",
    category: "Indian founder - YC",
    overlap: "Indian, very young, immigrant, built/exited young, now YC GP",
    waveDay: 9,
    subject: "An Indian Founder Following the Path You Paved",
    body: `<p>Hi Harshita,</p><p>You built and exited a product when you were young, came to the US on a visa to keep building, and now help decide who gets into YC, which reads almost exactly like the path I'm on right now, so I had to reach out to you specifically.</p><p>I'm Mehek, a USC computer science student building a vertical-AI company on my own and shipping in public as I go.</p><p>You're a few steps ahead on the exact road I'm walking, and what I'd most love to learn is what you think really stands between a product and a strong YC application. Could we find fifteen minutes this week? I'm at the start of this and ready to learn from how you did it.</p><p>Thank you, Harshita.</p><p>Mehek</p>`,
  },
  {
    name: "Eva Ho",
    email: "eva@fika.vc",
    category: "Female VC",
    overlap: "Refugee-immigrant, female, ex-founder, Fika Ventures GP, All Raise founder",
    waveDay: 9,
    subject: "An Immigrant Outsider Betting on Herself",
    body: `<p>Hi Eva,</p><p>You came up as an immigrant outsider, with none of the built-in access, and turned that into a seat where you now back founders, which is exactly the arc I think about as someone starting from outside the usual rooms.</p><p>I'm Mehek, 20, a USC computer science student building a vertical-AI company on my own, and your story is one of the clearest proofs I've found that the outsider path actually leads somewhere real.</p><p>That's exactly where I want to get to one day, and the part I'd most love to learn is where you'd tell a young founder they are thinking too small. I'd love to grab fifteen minutes with you this week to hear it. I'm right at the start and ready to learn from someone who has lived it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Shruti Gandhi",
    email: "shruti@array.vc",
    category: "Female VC",
    overlap: "Indian immigrant, ex-engineer, female, Array Ventures solo GP",
    waveDay: 9,
    subject: "An Indian Founder Following the Path You Paved",
    body: `<p>Hi Shruti,</p><p>You went from engineer to solo GP and built a fund that opens doors for the founders the system usually skips, which is exactly the kind of path I think about as an Indian immigrant building from outside the usual circles.</p><p>I'm Mehek, 20, a USC computer science student building a vertical-AI company on my own, and watching an engineer turn into a solo investor backing underrepresented founders is genuinely encouraging to me.</p><p>That's the kind of self-made path I want to be on, and what I'd most love to learn is what you'd tell an immigrant founder right at the very start. I'd love to grab fifteen minutes with you this week to hear it. I'm right there now and ready to learn from how you did it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Sarah Kunst",
    email: "sarah@cleocap.com",
    category: "Female VC",
    overlap: "Female, ex-founder championing overlooked founders, Cleo Capital MD",
    waveDay: 10,
    subject: "A Solo Female Founder, Right at the Start",
    body: `<p>Hi Sarah,</p><p>You built a whole fund to back the founders the system overlooks and underestimates, and as a solo female founder right at the beginning of this, that is exactly the kind of belief I've been looking for.</p><p>I'm Mehek, 20, a USC computer science student building a vertical-AI company on my own, and the way you bet on the people everyone else skips is the most encouraging thing I've read in a while.</p><p>That's exactly where I want to get to one day, and what I'd most love is the one piece of blunt advice you'd give a solo female founder in her first week. I'd love to grab fifteen minutes with you this week to hear it. I'm right there now and genuinely ready to learn.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Gabriel Jarrosson",
    email: "gabriel@lobstercap.com",
    category: "YC path mentor",
    overlap: "Solo founder to YC-only investor, bootstrapped to $1M ARR, teaches YC path openly",
    waveDay: 10,
    subject: "A Fellow Solo Founder on the YC Path",
    body: `<p>Hi Gabriel,</p><p>You bootstrapped solo, walked the YC path yourself, and now teach and back founders openly instead of gatekeeping it, which is exactly the road I'm on as a solo builder trying to do this right.</p><p>I'm Mehek, a USC computer science student building a vertical-AI company on my own and shipping in public as I go.</p><p>The part I'd most love to learn is the highest-leverage thing you did for your first real traction, because that's precisely the wall I'm at now. Could we find fifteen minutes this week? I'm at the start of this and genuinely ready to learn from how you did it.</p><p>Thank you, Gabriel.</p><p>Mehek</p>`,
  },
  {
    name: "Carina Hong",
    email: "carina@axiommath.ai",
    category: "Young vertical AI founder",
    overlap: "Immigrant, female, deep vertical AI, Stanford dropout, well-funded",
    waveDay: 10,
    subject: "A Fellow Young Founder Going Deep on One Vertical",
    body: `<p>Hi Carina,</p><p>You went truly deep on one hard vertical young, as an immigrant building from outside the usual rooms, which is almost exactly the lane I'm in right now, so I wanted to reach out to you specifically.</p><p>I'm Mehek, a USC computer science student building a vertical-AI company on my own, going deep on one domain the same focused way you did on yours.</p><p>The part I'd most love to learn is how you knew who to ask to mentor you, and how you actually made the ask, because that's the exact thing I'm trying to get right now. Could we find fifteen minutes this week? I'm at the start of this and genuinely ready to learn from how you did it.</p><p>Thank you, Carina.</p><p>Mehek</p>`,
  },
  {
    name: "Mariama Diallo",
    email: "mariama@aethexai.com",
    category: "Gulf AI founder",
    overlap: "Left Goldman, female, AI for the Gulf and emerging markets, $3M pre-seed",
    waveDay: 10,
    subject: "I Left Finance to Build, Like You Did",
    body: `<p>Hi Mariama,</p><p>You left Goldman to go build AI for the Gulf and emerging markets, the region everyone else overlooks, and as someone betting on building from outside the usual centers, that choice genuinely shifted how I think.</p><p>I'm Mehek, a USC computer science student building a vertical-AI company on my own, and watching someone leave a name like Goldman to build for an overlooked region is exactly the kind of bet I find inspiring.</p><p>The part I'd most love to learn is what changed in how you think about building after leaving Goldman. Could we find fifteen minutes this week? I'm at the very start of this and genuinely ready to learn from how you did it.</p><p>Warmly,<br>Mehek</p>`,
  },
  {
    name: "Sophia Zhao",
    email: "sophia.zhao@av.vc",
    category: "Female VC",
    overlap: "Immigrant kid, female, partner across AI fund and women's fund",
    waveDay: 10,
    subject: "A Small-Business Kid Now Building in AI",
    body: `<p>Hi Sophia,</p><p>You grew up in your parents' small business and turned that into a seat where you now back AI and women founders, which is exactly the kind of arc I think about as someone building from outside the usual rooms.</p><p>I'm Mehek, a USC computer science student building a vertical-AI company on my own, and the way you came up through a family business and now invest in women in AI is genuinely encouraging to me.</p><p>That's where I want to get to one day, and what I'd most love to learn is where you'd tell a young founder they are underbuilding. I'd love to grab fifteen minutes with you this week to hear it. I'm right at the start and ready to learn from how you did it.</p><p>Warmly,<br>Mehek</p>`,
  },
];
